name: Release a new version

# triggered manually
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version (e.g. 4.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.4
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Uploading built HTML file
        uses: actions/upload-artifact@v4
        with:
          name: twitch-polls
          path: build/index.html

  create-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - run: echo "Creating release ${{ github.event.inputs.releaseVersion }}"
      - uses: actions/checkout@v3
      - name: Using built HTML file
        uses: actions/download-artifact@v4
        with:
          name: twitch-polls
          path: ./
      - name: Rename file for release
        run: mv index.html twitch-polls-${{ github.event.inputs.releaseVersion }}.html
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: twitch-polls-${{ github.event.inputs.releaseVersion }}.html
          tag_name: v${{ github.event.inputs.releaseVersion }}
          name: Release ${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
          generate_release_notes: true
