name: Release a new version

# triggered manually
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version (e.g. 4.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.4
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Uploading built HTML file
        uses: actions/upload-artifact@v4
        with:
          name: twitch-polls
          path: build/index.html

  release-to-branch:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      # as per https://github.com/marketplace/actions/git-auto-commit
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - run: echo "Creating release ${{ github.event.inputs.releaseVersion }}"
      - uses: actions/checkout@v3
      - name: Using built HTML file
        uses: actions/download-artifact@v4
        with:
          name: twitch-polls
          path: release
      - name: Clean release directory
        run: |
          mv release/index.html ./twitch-polls.html
          git rm -rf ./*
          mv ./twitch-polls.html ./index.html
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add built file for release ${{ github.event.inputs.releaseVersion }}
          branch: release/${{ github.event.inputs.releaseVersion }}
          create_branch: true
          tagging_message: '${{ github.event.inputs.releaseVersion }}'
